version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-29
    steps:
      - checkout
      - run:
          name: Analyze with detekt
          command: ./gradlew detekt
          when: always
      - run:
          name: Analyze with ktlint
          command: ./gradlew ktlint
          when: always
      - run:
          name: Analyze with lint on debug build
          command: ./gradlew lintDebug
          when: always
      - store_artifacts:
          path: /home/circleci/project/app/build/reports/detekt/detekt.html
          destination: reports/detekt
      - store_artifacts:
          path: /home/circleci/project/app/build/ktlint.xml
          destination: reports/ktlint
      - store_artifacts:
          path: /home/circleci/project/app/build/reports/lint-results-debug.html
          destination: reports/android_lint
