version: 2.1

jobs:
  static_analyzers:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    steps:
      - checkout
      - run:
          name: androidLint(debug)
          command: ./gradlew lintDebug
          when: always
      - run:
          name: detekt
          command: ./gradlew detekt
          when: always
      - run:
          name: ktlint
          command: ./gradlew ktlint
          when: always
      - store_artifacts:
          path: /home/circleci/code/app/build/reports/detekt/detekt.html
          destination: reports/detekt
      - store_artifacts:
          path: /home/circleci/code/app/build/reports/lint-results-debug.html
          destination: reports/android_lint
      - store_artifacts:
          path: /home/circleci/code/app/build/ktlint.xml
          destination: reports/ktlint

  unit_tests:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    steps:
      - checkout
      - run:
          name: Unit tests
          command: ./gradlew test
          when: always
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
          destination: tests

  distribution:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    steps:
      - checkout
      - run:
          name: Distribute
          command: |
            export FIREBASE_TOKEN=$FIREBASE_TOKEN
            ./gradlew assembleDebug appDistributionUploadDebug
          when: always

workflows:
  version: 2
  on_commits:
    jobs:
      - static_analyzers
      - unit_tests
      - distribution:
          requires:
            - static_analyzers
            - unit_tests
          filters:
            branches:
              only:
                - master