version: 2.1

orbs:
  android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          command: ./gradlew clean
      - run:
          command: ./gradlew lintDebug
          when: always
      - run:
          command: ./gradlew detekt
          when: always
      - run:
          command: ./gradlew ktlint
          when: always
      - store_artifacts:
          path: /home/circleci/project/app/build/reports/detekt/detekt.html
      - store_artifacts:
          path: /home/circleci/project/app/build/reports/lint-results-debug.html
      - store_artifacts:
          path: /home/circleci/project/app/build/ktlint.xml