version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-29
    steps:
      - checkout
      - run: ./gradlew detekt
      - run: ./gradlew ktlint
      - run: ./gradlew lintDebug